language: php

php:
  - 5.5
  - 5.6
  - 7.0

env:
  global:
    - PLUGIN_NAME=PreFilter

  matrix:
    - CAKE_VERSION=2.7


install:
  - sh -c "if [ -n \"$CAKE_VERSION\" ]; then composer global require 'phpunit/phpunit=3.7.*'; fi"

before_script:
  - git clone https://github.com/FriendsOfCake/travis.git --depth 1 ../travis
  - ../travis/before_script.sh
  - sh -c "if [ -n \"$CAKE_VERSION\" ]; then ln -s ~/.composer/vendor/phpunit/phpunit/PHPUnit ../cakephp/vendors/PHPUnit; fi"

script:
  - ../travis/script.sh

after_success:
  - ../travis/after_success.sh

notifications:
  email: false
